services:
  wi-postgres:
    container_name: "wi-postgres"
    image: postgres:17.5-alpine3.22
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - ./backend/postgres_data:/var/lib/postgresql/data
    networks:
      - wi-network

  wi-be:
    container_name: "wi-be"
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - .env
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    networks:
      - wi-network
    depends_on:
      - wi-postgres
    restart: on-failure
    
networks:
  wi-network:
    name: wi-network
    driver: bridge